# Generated by Django 2.2.1 on 2019-07-05 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=10)),
                ('fullname', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=40)),
                ('director', models.CharField(max_length=100)),
                ('writer', models.CharField(max_length=100)),
                ('imdb', models.CharField(max_length=20)),
                ('douban', models.CharField(max_length=20)),
                ('rating', models.CharField(max_length=10)),
                ('actor', models.CharField(max_length=500)),
                ('cover', models.CharField(max_length=100)),
                ('is_movie', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdb', models.CharField(max_length=20)),
                ('filename', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=20)),
                ('quality', models.CharField(max_length=20)),
                ('magnet', models.CharField(max_length=500)),
            ],
        ),
    ]
